### ISSUE TITLE
Race condition in zk_loop and KazooClient destructor

### ISSUE THREAD

**Issue by wilmayeung** [python-zk/kazoo#217]
I hit the following from time to time on Ubuntu 14.04 while never hit this on OSX 10.9.4

Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
 File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
 File "/usr/lib/python2.7/threading.py", line 763, in run
 File "/opt/simcloud/src/third_party/build/lib/python2.7/site-packages/kazoo/protocol/connection.py", line 472, in zk_loop
 File "/usr/lib/python2.7/threading.py", line 585, in set
 File "/usr/lib/python2.7/threading.py", line 406, in notifyAll
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

There is a race condition in which if one doesn't call KazooClient.close() explicitly and KazooClient instance, its members, and other static instances may be destructed before the zk_loop exits.  In the case in which some instances of KazooClient are destructed before zk_loop exit, the above errors would be resulted.

The resolution would be to call KazooClient.stop() and close() explicitly within its destructor which doesn't exist yet.

**Comment by kislaykishore** [comment]
We are on RHEL7 and are facing this issue. Do we have any timelines for fixing this or any workarounds?

**Comment by bbangert** [comment]
A PR was merged to address this, does that fix it?

**Comment by bbangert** [comment]
Closing this as I'm not clear if it still applies.
