### ISSUE TITLE
'module' object has no attribute 'Queue'

### ISSUE THREAD

**Issue by yishenggudou** [python-zk/kazoo#239]
```
Traceback (most recent call last):
  File "spider_agent/conf.py", line 11, in <module>
    from kazoo.client import KazooClient
  File "/Library/Python/2.7/site-packages/kazoo/client.py", line 21, in <module>
    from kazoo.handlers.threading import SequentialThreadingHandler
  File "/Library/Python/2.7/site-packages/kazoo/handlers/threading.py", line 146, in <module>
    class SequentialThreadingHandler(object):
  File "/Library/Python/2.7/site-packages/kazoo/handlers/threading.py", line 177, in SequentialThreadingHandler
    queue_impl = Queue.Queue
AttributeError: 'module' object has no attribute 'Queue'
```

**Comment by Tianhuo007** [comment]
queue在python2和python3中不同：
  python2：q = Queue.Queue
  python3:   q = queue.Queue

**Comment by spmsupun** [comment]
> import Queue; Queue

Oh go you are right, i file name was queue.py,  i feel so stupid
