### ISSUE TITLE
Unhandled exception in connection loop

### ISSUE THREAD

**Issue by rgs1** [python-zk/kazoo#281]
In [zk-shell](https://github.com/rgs1/zk_shell), I started seeing this with Kazoo-2.0:

```
ERROR:kazoo.client:Unhandled exception in connection loop
Traceback (most recent call last):
  File "/home/rgs/.pex/install/kazoo-2.0-py2-none-any.whl.c310f8d552e1beaa6e01f51c4edb52176ed9452d/kazoo-2.0-py2-none-any.whl/kazoo/protocol/connection.py", line 529, in _connect_attempt
    self._send_ping(connect_timeout)
  File "/home/rgs/.pex/install/kazoo-2.0-py2-none-any.whl.c310f8d552e1beaa6e01f51c4edb52176ed9452d/kazoo-2.0-py2-none-any.whl/kazoo/protocol/connection.py", line 447, in _send_ping
    self._submit(PingInstance, connect_timeout, PING_XID)
  File "/home/rgs/.pex/install/kazoo-2.0-py2-none-any.whl.c310f8d552e1beaa6e01f51c4edb52176ed9452d/kazoo-2.0-py2-none-any.whl/kazoo/protocol/connection.py", line 275, in _submit
    if request.type:
AttributeError: 'NoneType' object has no attribute 'type'
```

Has anyone else seen this? I'll look for a consistent repro.

**Comment by rgs1** [comment]
This is actually quite bizarre: how PingInstance every be None?

**Comment by rgs1** [comment]
Haven't seen this again, so closing. Thx!
