### ISSUE TITLE
terminate managed cluster in kazoo.testing.harness by hand

### ISSUE THREAD

**Issue by tevino** [python-zk/kazoo#343]
```python
# test.py
import glob
from os import environ as env
from kazoo.testing.harness import get_global_cluster


if __name__ == '__main__':
    # These two lines set the zookeeper path to the default on my mac
    # which installed by brew, It has nothing to do with the error
    mac_default = glob.glob('/usr/local/Cellar/zookeeper/*/libexec')
    env['ZOOKEEPER_PATH'] = mac_default[0]

    c = get_global_cluster()
    c.terminate()  # comment this line
    # c.start()    # or uncomment this line
    # then the error disappears
```
Error message:
```shell
$ python test.py

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/tevin/.pyenv/versions/test/lib/python2.7/site-packages/kazoo/testing/harness.py", line 39, in <lambda>
    atexit.register(lambda cluster: cluster.terminate(), CLUSTER)
  File "/Users/tevin/.pyenv/versions/test/lib/python2.7/site-packages/kazoo/testing/common.py", line 279, in terminate
    server.destroy()
  File "/Users/tevin/.pyenv/versions/test/lib/python2.7/site-packages/kazoo/testing/common.py", line 227, in destroy
    shutil.rmtree(self.working_path)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/var/folders/2t/lzykg8416879hv55w99wzn280000gn/T/tmpBCZsPi'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/tevin/.pyenv/versions/test/lib/python2.7/site-packages/kazoo/testing/harness.py", line 39, in <lambda>
    atexit.register(lambda cluster: cluster.terminate(), CLUSTER)
  File "/Users/tevin/.pyenv/versions/test/lib/python2.7/site-packages/kazoo/testing/common.py", line 279, in terminate
    server.destroy()
  File "/Users/tevin/.pyenv/versions/test/lib/python2.7/site-packages/kazoo/testing/common.py", line 227, in destroy
    shutil.rmtree(self.working_path)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/var/folders/2t/lzykg8416879hv55w99wzn280000gn/T/tmpBCZsPi'
```

**Comment by tevino** [comment]
PR: #341
