### ISSUE TITLE
How to reconnect when client state is SUSPENDED or LOST

### ISSUE THREAD

**Issue by lixiaoyu-code** [python-zk/kazoo#357]
``` python

zk = KazooClient()
zk.start()

while True:
    # call kazoo.client.delete
    # call kazoo.client.set
    # call kazoo.client.get        
```

but after running for some time, raise exception like this

``` python
Traceback (most recent call last):
  File "/home/.../zookeeper.py", line 146, in _delete
    zk.delete(path,version,True)
  File "/home/.../kazoo-2.2.1-py2.7.egg/kazoo/client.py", line 1293, in delete
    return self.delete_async(path, version).get()
  File "/home/.../kazoo-2.2.1-py2.7.egg/kazoo/handlers/utils.py", line 78, in get
    raise self._exception
ConnectionLoss
```

**Comment by tigran-a** [comment]
Experience similar issue by using pykafka https://github.com/Parsely/pykafka/issues/369 . Zookeeper is clustered on two nodes

**Comment by jeffwidman** [comment]
I think this is explained in the docs: https://kazoo.readthedocs.io/en/latest/basic_usage.html#listening-for-connection-events
