### ISSUE TITLE
kazoo/client.py in python2.7 use KazooClient init throw a error 

### ISSUE THREAD

**Issue by lee-yong** [python-zk/kazoo#749]
trace back info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/testbase/loader.py", line 161, in _load
    __import__(modulename)
  File "/data/qctestproj/tcetest/setup/AddAccountTest.py", line 23, in <module>
    from tcelib.setup.common import update_jsonfile
  File "/data/qctestproj/tcelib/setup/common.py", line 10, in <module>
    from qclib.business.cvm import CVMV3
  File "/data/qctestproj/qclib/business/cvm.py", line 44, in <module>
    from qclib.host import LinuxSSHSession, WindowsRMSession, TCEWindowsRMSession
  File "/data/qctestproj/qclib/host.py", line 29, in <module>
    from qclib.business.vpc_oss.vpcoss import VpcOssCtrl
  File "/data/qctestproj/qclib/business/vpc_oss/vpcoss.py", line 13, in <module>
    from qclib.zkclient import ZKClient
  File "/data/qctestproj/qclib/zkclient.py", line 9, in <module>
    from kazoo.client import KazooClient
  File "/usr/lib/python2.7/site-packages/kazoo/client.py", line 123
    **kwargs,
            ^
SyntaxError: invalid syntax

troubleshooting:
maybe the __init__ parms has a "," after **kwargs

## Specifications

  - Kazoo version: 2.10.0
  - Python version: 2.7
  - OS: centos6.8

**Comment by StephenSorriaux** [comment]
Hello,

Python 2.7 support was dropped with kazoo 2.8.X. Please use `kazoo==2.7.0` if you can't upgrade your version of Python.
